### ISSUE TITLE
encrypt by device id or email has different should produce different results

### ISSUE THREAD

**Issue by xiaoqiangwang** [zhansliu/writemdict#1]
First of all. Thanks for the great work. Encryption is the hardest piece before full reveal of MDict file format.

Using MdxKeyGen,exe, it generates different RegCode for email and device id, even though the same string is provided. Eg. 
C:\>MdxKeyGen.exe xiaoqiangwang user@example.com
Author DictKey=xiaoqiangwang
Owner Email=user@example.com
Reg code for end user=3D46FE973BDCE216667011423A29AC80

C:\>MdxKeyGen.exe /d xiaoqiangwang user@example.com
Author DictKey=xiaoqiangwang
Device ID=user@example.com
Reg code for end user=D49DF8B49DFD45212DDDCA2C11B59174

And encrypt_key actually produces the same as what MdxKeyGen.exe does for Device ID,
In [4]: import writemdict
In [5]: writemdict.encrypt_key('xiaoqiangwang', 'user@example.com')
Out[5]: u'D49DF8B49DFD45212DDDCA2C11B59174'

**Comment by zhansliu** [comment]
It's true that encrypt_key doesn't agree with MdxKeyGen.exe, but I think this is just a bug in MdxKeyGen.exe — if you use the reg code from MdxKeyGen.exe, the file fails to open in MDict, at least on the platforms I tested it on (PC and Android). The reg code from encrypt_key does work, however.

The difference is that MdxKeyGen.exe encodes the e-mail address in UTF-16 before hashing it, whereas encrypt_key (and the official MDict clients) seem to use ASCII-encoded e-mail addresses.

**Comment by xiaoqiangwang** [comment]
I implemented it, as suggested, into readmdict.py. I tested it using email encrypted mdx file and it works.

On the other hand, mdict encryption can be bypassed. I have implemented that inside the  MDict._read_keys_brutal method.

It seems now the mdx/mdd is fully understood. Thanks for sharing!

**Comment by kejinlu** [comment]
@xiaoqiangwang  我想咨询您一个问题 https://bitbucket.org/xwang/mdict-analysis/src/master/ 里面提到的 mdx 3.0的版本（MdxBuilder 4.0 RC4 生成的）中，mdx文件格式被重构了，我想问下mdd资源文件的格式还是和之前的版本保持一致没有变化么？ 因为我看到你的文档里没有提到，非常期待您的解答，提前感谢您。


I'd like to inquire about something mentioned in the MDX 3.0（build by MdxBuilder 4.0 RC4） section of this repository: https://bitbucket.org/xwang/mdict-analysis/src/master/. It states that the MDX file format was refactored. My question is: Has the MDD resource file format remained consistent with previous versions, or has it also changed? I ask because I didn't see any mention of MDD changes in the documentation.

**Comment by xiaoqiangwang** [comment]
新的 mdd 和 mdx 的解析是一样的，都是 V3 格式。
> [@xiaoqiangwang](https://github.com/xiaoqiangwang) 我想咨询您一个问题 https://bitbucket.org/xwang/mdict-analysis/src/master/ 里面提到的 mdx 3.0的版本（MdxBuilder 4.0 RC4 生成的）中，mdx文件格式被重构了，我想问下mdd资源文件的格式还是和之前的版本保持一致没有变化么？ 因为我看到你的文档里没有提到，非常期待您的解答，提前感谢您。
>

**Comment by kejinlu** [comment]
> 新的 mdd 和 mdx 的解析是一样的，都是 V3 格式。
> 
> > [@xiaoqiangwang](https://github.com/xiaoqiangwang) 我想咨询您一个问题 https://bitbucket.org/xwang/mdict-analysis/src/master/ 里面提到的 mdx 3.0的版本（MdxBuilder 4.0 RC4 生成的）中，mdx文件格式被重构了，我想问下mdd资源文件的格式还是和之前的版本保持一致没有变化么？ 因为我看到你的文档里没有提到，非常期待您的解答，提前感谢您。

多谢多谢，也就是现在我们可以做到v3格式字典的完全解析对吧？
