### ISSUE TITLE
mdict supports duplicate keys

### ISSUE THREAD

**Issue by seaspeak** [zhansliu/writemdict#2]
mdict supports duplicate keys, but the python standard dict doesn't. a list with tuple elements in the demo script.

**Comment by nikita-moor** [comment]
Dear @seaspeak, could you reopen this issue, please, or explain how did you solve the problem? I have a dictionary with dozens or duplicate keys.

**Comment by nikita-moor** [comment]
It is enough to change [one line][1]:
```patch
--- writemdict.py
+++ writemdict.py
@@ -278,7 +278,7 @@
 		#  e.record_null: encoded version of the record, null-terminated
 		#
 		# Also sets self._total_record_len to the total length of all record fields.
-		items = list(d.items())
+		items = d.copy()
 		items.sort(key=operator.itemgetter(0))
 		
 		self._offset_table = []
```

[1]: https://github.com/liuyug/mdict-utils/blob/8332a8d75e11a2a364284fe88fc100daa9684c83/mdict_utils/base/writemdict.py#L281
